-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Corporates"
(
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Website" character(1) NOT NULL,
    "CompanyName" character varying(50) NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."IndividualJobPositions"
(
    "Id" integer NOT NULL,
    "IndividualId" integer NOT NULL,
    "JobPositionId" integer NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Individuals"
(
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "NationalIdentity" character(15) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    "UserId" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."JobPositions"
(
    "Id" integer NOT NULL,
    "Name" character varying(25) NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."PhoneNumbers"
(
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "PhoneNumber" character(15) NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Users"
(
    "Id" integer NOT NULL,
    "Email" character(50) NOT NULL,
    "Password" character varying(500) NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."Corporates"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."IndividualJobPositions"
    ADD FOREIGN KEY ("JobPositionId")
    REFERENCES public."JobPositions" ("Id")
    NOT VALID;


ALTER TABLE public."IndividualJobPositions"
    ADD FOREIGN KEY ("IndividualId")
    REFERENCES public."Individuals" ("Id")
    NOT VALID;


ALTER TABLE public."Individuals"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."PhoneNumbers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;

END;